apiVersion: v1
kind: Service
metadata:
  name: hoooq-ui
  labels:
    {{- include "hoooq-charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hoooq-charts.selectorLabels" . | nindent 4 }}
