apiVersion: v1
kind: ConfigMap
metadata:
  name: hoooq-idm
data:
  SECRET_DOMAIN_JWKS: {{ .Values.hoooq_idm.secret_domain_jwks }}
  PROJECT_URL: http://hoooq-idm
  PREFIX_NOTIFY_HOOOQ: hoooq.idm
  HOOOQ_URL: http://hoooq-core
  LIST_OF_CLAIMS: {{ .Values.hoooq_idm.list_of_claims }}
  HOOOQ_IDM_DB_USER_ATTRIBUTE_EMAIL: {{ .Values.hoooq_idm.hoooq_idm_db_user_attribute_email }}
  HOOOQ_IDM_DB_USER_ATTRIBUTE_NAME: {{ .Values.hoooq_idm.hoooq_idm_db_user_attribute_name }}
  HOOOQ_IDM_DB_USER_ATTRIBUTE_PASSWORD: {{ .Values.hoooq_idm.hoooq_idm_db_user_attribute_password }}
  HOOOQ_IDM_DB_USER_ATTRIBUTE_AVATAR: {{ .Values.hoooq_idm.hoooq_idm_db_user_attribute_avatar }}
  HOOOQ_IDM_DB_USER_ATTRIBUTE_DETAIL: {{ .Values.hoooq_idm.hoooq_idm_db_user_attribute_detail }}
  HOOOQ_IDM_DB_USER_ATTRIBUTE_CLAIMS: {{ .Values.hoooq_idm.hoooq_idm_db_user_attribute_claims }}
  HOOOQ_IDM_DB_USER_ATTRIBUTE_LAST_LOGIN: {{ .Values.hoooq_idm.hoooq_idm_db_user_attribute_last_login }}
  HOOOQ_IDM_DB_USER_ATTRIBUTE_CREATEDAT: {{ .Values.hoooq_idm.hoooq_idm_db_user_attribute_createdat }}
  HOOOQ_IDM_DB_USER_ATTRIBUTE_TWO_FA_SECRET: {{ .Values.hoooq_idm.hoooq_idm_db_user_attribute_two_fa_secret }}
  HOOOQ_IDM_DB_USER_ATTRIBUTE_EMAIL_VERIFIED_AT: {{ .Values.hoooq_idm.hoooq_idm_db_user_attribute_email_verified_at }}
  HOOOQ_IDM_DB_USER_ATTRIBUTE_EMAIL_VERIFIED_CODE: {{ .Values.hoooq_idm.hoooq_idm_db_user_attribute_email_verified_code }}
  HOOOQ_IDM_DB_USER_COLLECTION: {{ .Values.hoooq_idm.hoooq_idm_db_user_collection }}
  HOOOQ_IDM_DB_PARAMETER_ATTRIBUTE_KEY: {{ .Values.hoooq_idm.hoooq_idm_db_parameter_attribute_key }}
  HOOOQ_IDM_DB_PARAMETER_ATTRIBUTE_VALUE: {{ .Values.hoooq_idm.hoooq_idm_db_parameter_attribute_value }}
  HOOOQ_IDM_DB_PARAMETER_COLLECTION: {{ .Values.hoooq_idm.hoooq_idm_db_parameter_collection }}
  SECURITY_JWK_KEY_STORE: {{ .Values.hoooq_idm.security_jwk_key_store }}
  SECURITY_JWK_ROTATE_IN_DAYS: "{{ .Values.hoooq_idm.security_jwk_rotate_in_days }}"
  SECURITY_JWK_ROTATE_SIZE: "{{ .Values.hoooq_idm.security_jwk_rotate_size }}"
  JWT_EXPIRATION_MS: "{{ .Values.hoooq_idm.jwt_expiration_ms }}"
  FRONTEND_REDIRECT_URL: {{ .Values.hoooq_idm.frontend_redirect_url }}
  AUTHORIZATION_CODE_EXPIRE_IN_MINUTES: "{{ .Values.hoooq_idm.authorization_code_expire_in_minutes }}"
