apiVersion: v1
kind: ConfigMap
metadata:
  name: hoooq-ws
data:
  MQTT_PORT: "{{ .Values.mqtt.mqtt_port }}"
  MQTT_HOST: {{ .Values.mqtt.mqtt_host }}
  SECRET_DOMAIN_JWKS: {{ .Values.hoooq_ws.secret_domain_jwks }}
  PROJECT_URL: http://hoooq-ws
  PREFIX_NOTIFY_HOOOQ: hoooq.ws
  HOOOQ_URL: http://hoooq-core
  LIST_OF_CLAIMS: {{ .Values.hoooq_ws.list_of_claims }}