apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |-
    listener {{ .Values.mqtt.mqtt_port }}
    allow_anonymous true
    socket_domain ipv4

---

apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mqtt.mqtt_port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    app.kubernetes.io/name: mosquitto

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:  
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mosquitto
    spec:
      serviceAccountName: {{ include "hoooq-charts.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: mosquitto
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "eclipse-mosquitto"
          imagePullPolicy: IfNotPresent

          ports:
            - name: tcp
              containerPort: {{ .Values.mqtt.mqtt_port }}
              protocol: TCP

          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf

          resources: {}
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config

