apiVersion: v1
kind: Service
metadata:
  name: hoooq-ws
  labels: {{ .Values.service.labels | toYaml | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: hoooq-ws
