{{- if eq .Values.database.provider "postgres" -}}
{{- if eq .Values.database.database_host "postgres" -}}
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.database_port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    app.kubernetes.io/name: postgres

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:  
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
    spec:
      serviceAccountName: {{ include "hoooq-charts.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: postgres
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "postgres"
          imagePullPolicy: IfNotPresent
          env:
          - name: POSTGRES_PASSWORD
            value: {{ .Values.database.database_password }}
          - name: POSTGRES_DB
            value: {{ .Values.database.database_name }}
          ports:
            - name: tcp
              containerPort: {{ .Values.database.database_port }}
              protocol: TCP
          resources: {}
{{- end }}
{{- end }}