
apiVersion: v1
kind: Secret
metadata:
  name: hoooq-core
data:
  SECRET_KEY: WVdKak1USXpkdz09
  JWT_EXPIRATION: MzYwMA==
  RABBITMQ_USERNAME: {{ .Values.broker.rabbitmq_username | b64enc }}
  RABBITMQ_PASSWORD: {{ .Values.broker.rabbitmq_password | b64enc }}
  DEFAULT_USER: {{ .Values.hoooq_core.default_user | b64enc }}
  DEFAULT_PASSWORD: {{ .Values.hoooq_core.default_password | b64enc }}
  DEFAULT_APP_USER: {{ .Values.hoooq_core.default_app_user | b64enc }}
  DEFAULT_APP_PASSWORD: {{ .Values.hoooq_core.default_app_password | b64enc }}
  DEFAULT_GUEST_USER: {{ .Values.hoooq_core.default_guest_user | b64enc }}
  DEFAULT_GUEST_PASSWORD: {{ .Values.hoooq_core.default_guest_password | b64enc }}
  {{ if .Values.database.database_uri }}
  DATABASE_URI: "{{ .Values.database.database_uri | b64enc }}"
  {{ else }}
  DATABASE_USERNAME: {{ .Values.database.database_username | b64enc }}
  DATABASE_PASSWORD: {{ .Values.database.database_password | b64enc }}
  {{ end }}
type: Opaque


