
apiVersion: v1
kind: Secret
metadata:
  name: hoooq
data:
  SECRET_KEY: WVdKak1USXpkdz09
  JWT_EXPIRATION: NjAw
  RABBITMQ_USERNAME: {{ .Values.broker.rabbitmq_username | b64enc }}
  RABBITMQ_PASSWORD: {{ .Values.broker.rabbitmq_password | b64enc }}
  DATABASE_USERNAME: {{ .Values.repository.database_username | b64enc }}
  DATABASE_PASSWORD: {{ .Values.repository.database_password | b64enc }}
  DEFAULT_USER: {{ .Values.user.default_user | b64enc }}
  DEFAULT_PASSWORD: {{ .Values.user.default_password | b64enc }}
  DEFAULT_APP_USER: {{ .Values.user.default_app_user | b64enc }}
  DEFAULT_APP_PASSWORD: {{ .Values.user.default_app_password | b64enc }}
  DEFAULT_GUEST_USER: {{ .Values.user.default_guest_user | b64enc }}
  DEFAULT_GUEST_PASSWORD: {{ .Values.user.default_guest_password | b64enc }}
type: Opaque


