
apiVersion: v1
kind: Secret
metadata:
  name: hoooq-idm
data:
  HOOOQ_USERNAME: {{ .Values.hoooq_idm.hoooq_username | b64enc }}
  HOOOQ_PASSWORD: {{ .Values.hoooq_idm.hoooq_password | b64enc }}
  MONGO_URI: "{{ .Values.hoooq_idm.mongo_uri | b64enc }}"
type: Opaque
